### ISSUE TITLE
Audiobook PDF

### ISSUE THREAD

**Issue by DigitalExtension** [PacktPublishing/Learn-Computer-Forensics-Audiobook#1]
Hello,

I'm a student with access to Learn Computer Forensics audiobook. The audio instructions told us to navigate here to download the supplemental PDF, but there's nothing here. 

Please help me get the pdf.

Thank you,
Stephanie

**Comment by yashi-packt** [comment]
Hey Stephanie (@DigitalExtension), 

Could you refresh and check? We've uploaded the PDF again.

Thanks,
Yashi

**Comment by DigitalExtension** [comment]
Awesome. It's there now.
Thank you so much.
-Stephanie
